import * as THREE from '/public/vendor/three.module.js';
import {buildFlight,buildOrbit,buildCamera} from './games.js';

const canvas=document.querySelector('#world'), hub=document.querySelector('#hub'), hud=document.querySelector('#gameHud');
const nameEl=document.querySelector('#hudName'), objectiveEl=document.querySelector('#hudObjective'), scoreEl=document.querySelector('#score'), timerEl=document.querySelector('#timer'), progressFill=document.querySelector('#progressFill'), hintEl=document.querySelector('#controlsHint'), toastEl=document.querySelector('#toast'), mobileControls=document.querySelector('#mobileControls'), crosshair=document.querySelector('#crosshair');
const gameMeta={flight:{index:'01',name:'קו הרקיע',objective:'12 טבעות. קו טיסה אחד.',hint:'הטס את הרחפן בין המגדלים. אסוף 12 טבעות אור.'},orbit:{index:'02',name:'המסלול האחרון',objective:'שברי אור מחכים במסלול.',hint:'קרב את המסלול שלך לטבעת. שנה גובה כדי לפגוש את השברים.'},camera:{index:'03',name:'במאי התנועה',objective:'פריים ראשון. הזמן שלך מתחיל.',hint:'זוז סביב הדמות, שנה מרחק עם W/S וצלם ב־Space.'}};
const games={flight:buildFlight,orbit:buildOrbit,camera:buildCamera};
let renderer,camera,scene,current,activeId=null,startedAt=0,elapsed=0,muted=false,toastTimer=0,lastFrame=0;
const keys=new Set(), clock=new THREE.Clock();

function makeRenderer(){try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.18;renderer.info.autoReset=false;camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,800);return true;}catch(err){document.body.insertAdjacentHTML('beforeend','<div class="no-webgl"><div><h2>העולם הזה צריך WebGL</h2><p>פתח את המשחק בדפדפן מעודכן והפעל האצת חומרה.</p></div></div>');return false;}}
function material(color,emissive=0,extra={}){return new THREE.MeshStandardMaterial({color,emissive,emissiveIntensity:emissive?1.3:0,metalness:.38,roughness:.5,...extra});}
function makeHubScene(){const s=new THREE.Scene();s.background=new THREE.Color(0x0a1011);s.fog=new THREE.FogExp2(0x0a1011,.008);s.add(new THREE.HemisphereLight(0xc4dbd2,0x1c2024,1.7));const key=new THREE.DirectionalLight(0xcafa79,2.6);key.position.set(-20,38,18);s.add(key);const fill=new THREE.PointLight(0x45bcc5,60,100);fill.position.set(14,7,-18);s.add(fill);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(260,260),material(0x172022));floor.rotation.x=-Math.PI/2;floor.position.y=-.15;s.add(floor);const grid=new THREE.GridHelper(180,54,0x6a8f82,0x263936);grid.position.y=-.13;grid.material.transparent=true;grid.material.opacity=.37;s.add(grid);
  const ringMat=material(0xb8f35b,0x78a924,{roughness:.28,metalness:.46});for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(5.6+i*1.3,.08,8,96),ringMat);ring.position.set((i-1)*15,5+Math.sin(i)*2,-12-i*8);ring.rotation.set(.35+i*.21,0,.2-i*.17);s.add(ring);const light=new THREE.PointLight([0xb8f35b,0x81e5d8,0xff9f73][i],18,25);light.position.copy(ring.position);s.add(light);}
  const rnd=(()=>{let x=501;return()=>((x=Math.imul(x,1664525)+1013904223)>>>0)/4294967296;})();for(let i=0;i<120;i++){const h=4+rnd()*20,x=(rnd()-.5)*130,z=-rnd()*110;const b=new THREE.Mesh(new THREE.BoxGeometry(4+rnd()*8,h,4+rnd()*8),material(new THREE.Color().setHSL(.49+rnd()*.07,.12,.1+rnd()*.08)));b.position.set(x,h/2-.1,z);s.add(b);}
  camera.position.set(0,18,62);camera.lookAt(0,5,-20);return s;}
function playTone(freq=660,duration=.12){if(muted)return;try{const AC=window.AudioContext||window.webkitAudioContext;const ctx=playTone.ctx||(playTone.ctx=new AC());if(ctx.state==='suspended')ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.setValueAtTime(.045,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+duration);}catch{}}
function showToast(text){toastEl.textContent=text;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),1250);playTone(790,.1);}
function destroyScene(target){if(!target)return;target.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material){for(const v of Array.isArray(o.material)?o.material:[o.material])v.dispose();}});}
function setHome(){if(activeId)destroyScene(scene);activeId=null;current=null;keys.clear();scene=makeHubScene();renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.65));camera.position.set(0,18,62);camera.lookAt(0,5,-20);hub.classList.remove('leaving');hud.classList.remove('visible');mobileControls.classList.remove('visible');crosshair.classList.remove('visible');document.body.classList.remove('in-game');}
function startGame(id){if(!games[id])return;destroyScene(scene);activeId=id;keys.clear();scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(id==='camera'?42:55,innerWidth/innerHeight,.1,700);camera.position.set(0,8,24);
  const meta=gameMeta[id];nameEl.textContent=meta.name;objectiveEl.textContent=meta.objective;hintEl.textContent=meta.hint;document.querySelector('#hudIndex').textContent=meta.index;scoreEl.textContent='000';timerEl.textContent='00:00';progressFill.style.width='0%';toastEl.classList.remove('show');elapsed=0;startedAt=performance.now();
  const state={score:0,progress:0,done:false,onAction:null,points(n,msg){this.score=Math.max(0,this.score+n);scoreEl.textContent=String(this.score).padStart(3,'0');showToast(msg);},progress(v){progressFill.style.width=Math.round(THREE.MathUtils.clamp(v,0,1)*100)+'%';},objective(v){if(objectiveEl.textContent!==v)objectiveEl.textContent=v;},complete(msg){if(this.done)return;this.done=true;progressFill.style.width='100%';hintEl.textContent=msg+' · לחץ Space כדי לחזור';showToast(msg);},camera};
  current=games[id](scene,state);current.state=state;hub.classList.add('leaving');hud.classList.add('visible');mobileControls.classList.add('visible');document.querySelector('#actionButton').classList.toggle('active',id==='camera');if(id==='camera')crosshair.classList.add('visible');else crosshair.classList.remove('visible');document.body.classList.add('in-game');setTimeout(()=>{hub.style.display='none';},380);playTone(520,.16);
}
function goHome(){hub.style.display='flex';setHome();}
function action(){if(!current)return;if(current.state.done){goHome();return;}if(current.state.onAction)current.state.onAction();}
document.querySelectorAll('[data-game]').forEach(el=>el.addEventListener('click',()=>startGame(el.dataset.game)));
document.querySelector('#jumpIn').addEventListener('click',()=>document.querySelector('.game-grid').scrollIntoView({behavior:'smooth',block:'center'}));
document.querySelector('#backButton').addEventListener('click',goHome);
document.querySelector('#actionButton').addEventListener('click',action);
document.querySelector('#soundToggle').addEventListener('click',e=>{muted=!muted;e.currentTarget.classList.toggle('muted',muted);if(!muted)playTone(700,.1);});
document.querySelectorAll('.mobile-controls button').forEach(b=>{const down=e=>{e.preventDefault();keys.add(b.dataset.key);},up=e=>{e.preventDefault();keys.delete(b.dataset.key);};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up);});
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&activeId){goHome();return;}if(e.code==='Space'){if(!keys.has('Space'))action();keys.add('Space');return;}keys.add(e.code);});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>keys.clear());
window.addEventListener('resize',()=>{if(!renderer)return;renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
function frame(now){requestAnimationFrame(frame);if(!renderer||!scene)return;const dt=Math.min(.045,Math.max(0,(now-lastFrame)/1000||0));lastFrame=now;
  if(current){elapsed=(now-startedAt)/1000;const mm=String(Math.floor(elapsed/60)).padStart(2,'0'),ss=String(Math.floor(elapsed%60)).padStart(2,'0');timerEl.textContent=mm+':'+ss;if(!current.state.done)current.update(dt,keys);}
  else{camera.position.x=Math.sin(now*.00006)*1.8;camera.lookAt(0,5,-20);}
  renderer.info.reset();renderer.render(scene,camera);
}

if(makeRenderer()){setHome();window.__game={get ready(){return Boolean(renderer&&scene)},get state(){return {screen:activeId?'playing':'hub',game:activeId,score:current?.state.score||0,progress:current?.progress||0,done:current?.state.done||false};},tick(n=1){for(let i=0;i<n;i++){renderer.info.reset();if(current&&!current.state.done)current.update(1/60,keys);renderer.render(scene,camera);}},info(){const gl=renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),game:activeId};},start:startGame,home:goHome,act:action};requestAnimationFrame(frame);}
